title: The Fridge Experiment
logo: /assets/logo.jpg
plugins:
  - jekyll-remote-theme
remote_theme: https://github.com/mmistakes/minimal-mistakes
description: A cool office fridge to keep our favourite co-workers refreshed